// <auto-generated />
using BillPlzAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillPlzAPI.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20181121024039_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BillPlzAPI.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Height");

                    b.Property<int>("ItemCount");

                    b.Property<string>("ItemName");

                    b.Property<int>("ItemPrice");

                    b.Property<string>("ItemURL");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Width");

                    b.HasKey("ItemId");

                    b.ToTable("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
